#!/bin/bash

source ~/.ion.conf

if [ "$1" = "-h" ] ; then
	echo -e "\n$0 v1 - konwerter IonCUBE dla systemu maszyn wirtualnych Comea.pl\n";
	echo -e "\tSkrypt przesyła archiwum TAR(lub inny) na daleką maszyne, gdzie następuje";
	echo -e "\tjego obróbka. Następnie odbiera plik wynikowy.\n";
	echo -e "\tPytania i takie tam: bartek@comea.pl\n";
	exit 0;
fi;

if [ -z "$1" -o -z "$2" ]; then 
	echo -e "Usage:\n\t$0 input_file.tar output_file.tar\ntype:\n\t$0 -h\nto get help(in polish)";
	exit 1;
fi
# Plik wejściowy
input_file=$1
# Plik wynikowy
output_file=$2

# Obcinanie do nazwy pliku
in=`basename "${input_file}"`
out=`basename "${output_file}"`

# Zdalny katalog roboczy
remote_dir=`ssh -p ${encoder_port} ${encoder_user}@${encoder_address} "mktemp -d /tmp/IonENCODER-request.XXXXXX"`

# Kopiowanie pliku
echo "Transfer na maszyne kodera..." 
scp -P ${encoder_port} "${input_file}" ${encoder_user}@${encoder_address}:"${remote_dir}/${in}"

# Lista poleceń obróbki
echo "Kodowanie..."
ssh -p ${encoder_port} -T ${encoder_user}@${encoder_address} "
	echo \"Kodowanie na \`uname -no\`\";
	cd \"${remote_dir}\";
	mkdir input_d;
	cd input_d;
	tar -xf \"../${in}\";
	cd ..;
	echo \"Kodowanie właściwe...\";
	${encodr_program} input_d -o output_d;
	echo \"Kodowanie zakończone...\";
	cd output_d;
	tar -cf \"../${out}\" . ;
"

# Pobieranie pliku wynikowego
echo "Odbieranie pliku wynikowego..."
scp -P ${encoder_port} ${encoder_user}@${encoder_address}:"${remote_dir}/${out}" "${output_file}"

# Usuwanie zdalnego katalogu roboczego
echo "Usuwanie plików roboczych z maszyny kodera..."
ssh -p ${encoder_port} ${encoder_user}@${encoder_address} "rm -rf ${remote_dir}"
