#!/bin/bash
source ~/.ion.conf
input_file=$1
output_file=$2

# Zdalny katalog roboczy
remote_dir=`ssh -p ${encoder_port} ${encoder_user}@${encoder_address} "mktemp -d /tmp/IonENCODER-request.XXXXXX"`

# Kopiowanie pliku
echo "Transfer na maszyne kodera..."
scp -P ${encoder_port} "${input_file}" ${encoder_user}@${encoder_address}:"${remote_dir}/${input_file}"

# Lista poleceń obróbki
echo "Kodowanie..."
ssh -p ${encoder_port} -T ${encoder_user}@${encoder_address} "
	echo \"Kodowanie na \`uname -no\`\";
	cd \"${remote_dir}\";
	${encodr_program} ${input_file} -o ${output_file};
	echo \"Kodowanie zakończone...\";
"
# Pobieranie pliku wynikowego
echo "Odbieranie pliku wynikowego..."
scp -P ${encoder_port} ${encoder_user}@${encoder_address}:"${remote_dir}/${output_file}" "${output_file}"

# Usuwanie zdalnego katalogu roboczego
echo "Usuwanie plików roboczych z maszyny kodera..."
ssh -p ${encoder_port} ${encoder_user}@${encoder_address} "rm -rf ${remote_dir}"
