#!/bin/bash
source ~/.ion.conf
keys=`ssh -T -p ${encoder_port} ${encoder_user}@${encoder_address} 'cat ~/.ssh/authorized_keys'`
selected=`zenity --text="Wybierz klucz do usunięcia" --separator=\  --list --hide-header --print-column=ALL --hide-column=2 --column="Type" --column="Value" --column="ID" ${keys}`
if [ -z "${selected}" ] ; then
	echo "Nie dokonano wyboru!"
	exit 1;
fi
echo "${keys}" | grep -v "${selected}" | ssh -T -p ${encoder_port} ${encoder_user}@${encoder_address} 'cat > ~/.ssh/authorized_keys'
